
[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[general]
import = ["~/.config/alacritty/everblush.toml"]

[env]
TERM = "xterm-256color"
